/* Generated By:JavaCC: Do not edit this line. NomParserConstants.java */
/*   Copyright (C) 2003-2007  University of Manchester
 *
 *   This library is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Lesser General Public
 *   License as published by the Free Software Foundation; either
 *   version 2.1 of the License, or (at your option) any later version.
 *
 *   This library is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with this library; if not, write to the Free Software
 *   Foundation, 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA. 
 *   (or see http://www.gnu.org/copyleft/lesser.html)
 */
package org.openscience.cdk.iupac.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NomParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int CONSTANT = 2;
  /** RegularExpression Id. */
  int DIGIT = 3;
  /** RegularExpression Id. */
  int DASH = 4;
  /** RegularExpression Id. */
  int COMMA = 5;
  /** RegularExpression Id. */
  int METH = 6;
  /** RegularExpression Id. */
  int ETH = 7;
  /** RegularExpression Id. */
  int PROP = 8;
  /** RegularExpression Id. */
  int BUT = 9;
  /** RegularExpression Id. */
  int UNDEC = 10;
  /** RegularExpression Id. */
  int EICOS = 11;
  /** RegularExpression Id. */
  int HENICOS = 12;
  /** RegularExpression Id. */
  int HEN = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int TRI = 15;
  /** RegularExpression Id. */
  int TETR = 16;
  /** RegularExpression Id. */
  int PENT = 17;
  /** RegularExpression Id. */
  int HEX = 18;
  /** RegularExpression Id. */
  int HEPT = 19;
  /** RegularExpression Id. */
  int OCT = 20;
  /** RegularExpression Id. */
  int NON = 21;
  /** RegularExpression Id. */
  int DEC = 22;
  /** RegularExpression Id. */
  int COS = 23;
  /** RegularExpression Id. */
  int CONT = 24;
  /** RegularExpression Id. */
  int A = 25;
  /** RegularExpression Id. */
  int SPACE = 26;
  /** RegularExpression Id. */
  int AN = 27;
  /** RegularExpression Id. */
  int EN = 28;
  /** RegularExpression Id. */
  int YN = 29;
  /** RegularExpression Id. */
  int YL = 30;
  /** RegularExpression Id. */
  int DI = 31;
  /** RegularExpression Id. */
  int CYCLO = 32;
  /** RegularExpression Id. */
  int CHLORO = 33;
  /** RegularExpression Id. */
  int FLUORO = 34;
  /** RegularExpression Id. */
  int BROMO = 35;
  /** RegularExpression Id. */
  int IODO = 36;
  /** RegularExpression Id. */
  int NITRO = 37;
  /** RegularExpression Id. */
  int OXO = 38;
  /** RegularExpression Id. */
  int PHENYL = 39;
  /** RegularExpression Id. */
  int AMINO = 40;
  /** RegularExpression Id. */
  int ALUMINO = 41;
  /** RegularExpression Id. */
  int LITHO = 42;
  /** RegularExpression Id. */
  int HYDROXY = 43;
  /** RegularExpression Id. */
  int E = 44;
  /** RegularExpression Id. */
  int OL = 45;
  /** RegularExpression Id. */
  int OICACID = 46;
  /** RegularExpression Id. */
  int OYLCHLORIDE = 47;
  /** RegularExpression Id. */
  int NITRILE = 48;
  /** RegularExpression Id. */
  int AL = 49;
  /** RegularExpression Id. */
  int AMIDE = 50;
  /** RegularExpression Id. */
  int AMINE = 51;
  /** RegularExpression Id. */
  int ONE = 52;
  /** RegularExpression Id. */
  int OATE = 53;
  /** RegularExpression Id. */
  int LITHIUM = 54;
  /** RegularExpression Id. */
  int SODIUM = 55;
  /** RegularExpression Id. */
  int POTASSIUM = 56;
  /** RegularExpression Id. */
  int RUBIDIUM = 57;
  /** RegularExpression Id. */
  int CESIUM = 58;
  /** RegularExpression Id. */
  int FRANCIUM = 59;
  /** RegularExpression Id. */
  int BERYLLIUM = 60;
  /** RegularExpression Id. */
  int MAGNESIUM = 61;
  /** RegularExpression Id. */
  int CALCIUM = 62;
  /** RegularExpression Id. */
  int STRONTIUM = 63;
  /** RegularExpression Id. */
  int BARIUM = 64;
  /** RegularExpression Id. */
  int RADIUM = 65;
  /** RegularExpression Id. */
  int SCANDIUM = 66;
  /** RegularExpression Id. */
  int YTTRIUM = 67;
  /** RegularExpression Id. */
  int LANTHANUM = 68;
  /** RegularExpression Id. */
  int ACTINIUM = 69;
  /** RegularExpression Id. */
  int TITANIUM = 70;
  /** RegularExpression Id. */
  int ZIRCONIUM = 71;
  /** RegularExpression Id. */
  int HAFNIUM = 72;
  /** RegularExpression Id. */
  int RUTHERFORDIUM = 73;
  /** RegularExpression Id. */
  int VANADIUM = 74;
  /** RegularExpression Id. */
  int NIOBIUM = 75;
  /** RegularExpression Id. */
  int TANTALUM = 76;
  /** RegularExpression Id. */
  int DUBNIUM = 77;
  /** RegularExpression Id. */
  int CHROMIUM = 78;
  /** RegularExpression Id. */
  int MOLYBDENUM = 79;
  /** RegularExpression Id. */
  int TUNGSTEN = 80;
  /** RegularExpression Id. */
  int SEABORGIUM = 81;
  /** RegularExpression Id. */
  int MANGANESE = 82;
  /** RegularExpression Id. */
  int TECHNETIUM = 83;
  /** RegularExpression Id. */
  int RHENIUM = 84;
  /** RegularExpression Id. */
  int BOHRIUM = 85;
  /** RegularExpression Id. */
  int IRON = 86;
  /** RegularExpression Id. */
  int RUTHENIUM = 87;
  /** RegularExpression Id. */
  int OSMIUM = 88;
  /** RegularExpression Id. */
  int HASSIUM = 89;
  /** RegularExpression Id. */
  int COBALT = 90;
  /** RegularExpression Id. */
  int RHODIUM = 91;
  /** RegularExpression Id. */
  int IRIDIUM = 92;
  /** RegularExpression Id. */
  int MEITMERIUM = 93;
  /** RegularExpression Id. */
  int NICKEL = 94;
  /** RegularExpression Id. */
  int PALLADIUM = 95;
  /** RegularExpression Id. */
  int PLATINUM = 96;
  /** RegularExpression Id. */
  int COPPER = 97;
  /** RegularExpression Id. */
  int SILVER = 98;
  /** RegularExpression Id. */
  int GOLD = 99;
  /** RegularExpression Id. */
  int ZINC = 100;
  /** RegularExpression Id. */
  int CADMIUM = 101;
  /** RegularExpression Id. */
  int MECURY = 102;
  /** RegularExpression Id. */
  int ALUMINIUM = 103;
  /** RegularExpression Id. */
  int GALLIUM = 104;
  /** RegularExpression Id. */
  int INDIUM = 105;
  /** RegularExpression Id. */
  int THALLIUM = 106;
  /** RegularExpression Id. */
  int GERMAINIUM = 107;
  /** RegularExpression Id. */
  int TIN = 108;
  /** RegularExpression Id. */
  int LEAD = 109;
  /** RegularExpression Id. */
  int ARSENIC = 110;
  /** RegularExpression Id. */
  int ANTIMONY = 111;
  /** RegularExpression Id. */
  int BISMUTH = 112;
  /** RegularExpression Id. */
  int SELENIUM = 113;
  /** RegularExpression Id. */
  int TELLURIUM = 114;
  /** RegularExpression Id. */
  int POLONIUM = 115;
  /** RegularExpression Id. */
  int CERIUM = 116;
  /** RegularExpression Id. */
  int PRASEODYMIUM = 117;
  /** RegularExpression Id. */
  int NEODYMIUM = 118;
  /** RegularExpression Id. */
  int PROMETHIUM = 119;
  /** RegularExpression Id. */
  int SANARIUM = 120;
  /** RegularExpression Id. */
  int EUROPIUM = 121;
  /** RegularExpression Id. */
  int GADOLINIUM = 122;
  /** RegularExpression Id. */
  int TERBIUM = 123;
  /** RegularExpression Id. */
  int DYSPROSIUM = 124;
  /** RegularExpression Id. */
  int HOLMIUM = 125;
  /** RegularExpression Id. */
  int ERBIUM = 126;
  /** RegularExpression Id. */
  int THULIUM = 127;
  /** RegularExpression Id. */
  int YTTERBIUM = 128;
  /** RegularExpression Id. */
  int LUTETIUM = 129;
  /** RegularExpression Id. */
  int THORIUM = 130;
  /** RegularExpression Id. */
  int PROTACTINIUM = 131;
  /** RegularExpression Id. */
  int URANIUM = 132;
  /** RegularExpression Id. */
  int NEPTUNIUM = 133;
  /** RegularExpression Id. */
  int PLUTONIUM = 134;
  /** RegularExpression Id. */
  int AMERCIUM = 135;
  /** RegularExpression Id. */
  int CURIUM = 136;
  /** RegularExpression Id. */
  int BERKELIUM = 137;
  /** RegularExpression Id. */
  int CALIFORNIUM = 138;
  /** RegularExpression Id. */
  int EINSTEINIUM = 139;
  /** RegularExpression Id. */
  int FERMIUM = 140;
  /** RegularExpression Id. */
  int MENDELEVIUM = 141;
  /** RegularExpression Id. */
  int NOBELIUM = 142;
  /** RegularExpression Id. */
  int LAWRENCIUM = 143;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "<CONSTANT>",
    "<DIGIT>",
    "\"-\"",
    "\",\"",
    "\"meth\"",
    "\"eth\"",
    "\"prop\"",
    "\"but\"",
    "\"undec\"",
    "<EICOS>",
    "\"henicos\"",
    "\"hen\"",
    "\"do\"",
    "\"tri\"",
    "\"tetra\"",
    "\"pent\"",
    "\"hex\"",
    "\"hept\"",
    "\"oct\"",
    "\"non\"",
    "\"dec\"",
    "\"cos\"",
    "\"cont\"",
    "\"a\"",
    "\" \"",
    "\"an\"",
    "\"en\"",
    "\"yn\"",
    "\"yl\"",
    "\"di\"",
    "\"cyclo\"",
    "\"chloro\"",
    "\"fluoro\"",
    "\"bromo\"",
    "\"iodo\"",
    "\"nitro\"",
    "\"oxo\"",
    "\"phenyl\"",
    "\"amino\"",
    "\"alumino\"",
    "\"litho\"",
    "\"hydroxy\"",
    "\"e\"",
    "\"ol\"",
    "\"oic acid\"",
    "\"oyl chloride\"",
    "\"nitrile\"",
    "\"al\"",
    "\"amide\"",
    "\"amine\"",
    "\"one\"",
    "\"oate\"",
    "\"lithium\"",
    "\"sodium\"",
    "\"potassium\"",
    "\"rubidium\"",
    "\"cesium\"",
    "\"francium\"",
    "\"beryllium\"",
    "\"magnesium\"",
    "\"calcium\"",
    "\"strontium\"",
    "\"barium\"",
    "\"radium\"",
    "\"scandium\"",
    "\"yttrium\"",
    "\"lanthanum\"",
    "\"actinium\"",
    "\"titanium\"",
    "\"zirconium\"",
    "\"hafnium\"",
    "\"rutherfordium\"",
    "\"vanadium\"",
    "\"niobium\"",
    "\"tantalum\"",
    "\"dubnium\"",
    "\"chromium\"",
    "\"molybdenum\"",
    "\"tungsten\"",
    "\"seaborgium\"",
    "\"manganese\"",
    "\"technetium\"",
    "\"rhenium\"",
    "\"bohrium\"",
    "\"iron\"",
    "\"ruthenium\"",
    "\"osmium\"",
    "\"hassium\"",
    "\"cobalt\"",
    "\"rhodium\"",
    "\"iridium\"",
    "\"meitmerium\"",
    "\"nickel\"",
    "\"palladium\"",
    "\"platinum\"",
    "\"copper\"",
    "\"silver\"",
    "\"gold\"",
    "\"zinc\"",
    "\"cadmium\"",
    "\"mercury\"",
    "\"aluminium\"",
    "\"gallium\"",
    "\"indium\"",
    "\"thallium\"",
    "\"germainium\"",
    "\"tin\"",
    "\"lead\"",
    "\"arsenic\"",
    "\"antimony\"",
    "\"bismuth\"",
    "\"selenium\"",
    "\"tellurium\"",
    "\"polonium\"",
    "\"cerium\"",
    "\"praseodymium\"",
    "\"neodymium\"",
    "\"promethium\"",
    "\"sanarium\"",
    "\"europium\"",
    "\"gadolinium\"",
    "\"terbium\"",
    "\"dysprosium\"",
    "\"holmium\"",
    "\"erbium\"",
    "\"thulium\"",
    "\"ytterbium\"",
    "\"lutetium\"",
    "\"thorium\"",
    "\"protactinium\"",
    "\"uranium\"",
    "\"neptunium\"",
    "\"plutonium\"",
    "\"amercium\"",
    "\"curium\"",
    "\"berkelium\"",
    "\"californium\"",
    "\"einsteinium\"",
    "\"fermium\"",
    "\"mendelevium\"",
    "\"nobelium\"",
    "\"lawrencium\"",
  };

}
